services:
  timetable:
    container_name: timetable
    build: 
      context: .
      dockerfile: Dockerfile
    image: timetable-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - timetable
    volumes:
      - ./dist:/timetable-api/dist  
      - ./package.json:/timetable-api/package.json
      - ./package-lock.json:/timetable-api/package-lock.json
      - ./.env.dev:/timetable-api/.env

  postgres:
    image: postgres:14.12
    restart: always
    container_name: postgres-timetable
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timetable
    ports:
      - '5433:5432'
    networks:
      - timetable
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scheme.sql:/docker-entrypoint-initdb.d/scheme.sql

  redis:
    image: redis
    container_name: redis-timetable
    ports:
      - "6380:6379"
    networks:
      - timetable
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  timetable:
    name: timetable
    driver: bridge

volumes:
  postgres_data:
